### ISSUE TITLE
Remote database not getting updated

### ISSUE THREAD

**Issue by wfendler** [demental/wp-deploy-flow#12]
When I run `wp deploy push staging` I don't get any errors and everything appears to be working but when I check my staging site only file updates have been pushed, no database changes.

What configurations might be wrong, or what could I give more details on in order to help troubleshoot this problem?

**Comment by demental** [comment]
Have you chrcked the générantes commands ?

Try wp deploy push staging --dry-run then execute each command manually and check expected result.

**Comment by demental** [comment]
If you still cannot identify the problem leave the generated commands here (don't forget to obfuscate your passwords)

**Comment by wfendler** [comment]
Thanks for the quick response.
I've done what you suggested and it looks like everything succeeded.

After looking into it some more, it looks like when wordpress was added to my staging location it was set up with a different table prefix. So, all of the updates were making it there but it just wasn't being used since `wp-config.php` was looking for `wp_` prefixed tables.

Apologies for the non-issue. Thanks for the help!
