### ISSUE TITLE
Use `wp search-replace`?

### ISSUE THREAD

**Issue by scribu** [demental/wp-deploy-flow#2]
I'm wondering if the `wp migrate to` command could be replaced with `wp search-replace`, which is built into WP-CLI.

This would remove two dependencies: 
- the WP Migrate DB plugin
- the `wp migrate` command for the plugin

**Comment by scribu** [comment]
Related: c10b10/wp-deploy-flow@cb783f2bf13174a984859e14a8551afb96d8287a

**Comment by DevinClark** [comment]
:+1:
